package entidades;
// Generated 13/05/2019 10:04:02 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private int idDetalleVenta;
     private Producto producto;
     private Venta venta;
     private int cantidad;
     private BigDecimal subtotal;

    public Detalleventa() {
    }

    public Detalleventa(int idDetalleVenta, Producto producto, Venta venta, int cantidad, BigDecimal subtotal) {
       this.idDetalleVenta = idDetalleVenta;
       this.producto = producto;
       this.venta = venta;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
    }
   
    public int getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(int idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }




}


