package entidades;
// Generated 13/05/2019 10:04:02 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int idVenta;
     private BigDecimal total;
     private Date fecha;
     private Set detalleventas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(int idVenta, BigDecimal total, Date fecha) {
        this.idVenta = idVenta;
        this.total = total;
        this.fecha = fecha;
    }
    public Venta(int idVenta, BigDecimal total, Date fecha, Set detalleventas) {
       this.idVenta = idVenta;
       this.total = total;
       this.fecha = fecha;
       this.detalleventas = detalleventas;
    }
   
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }




}


